sonar.projectKey=Cooooooler_lucy
sonar.organization=cooooooler
sonar.projectName=lucy

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Paths are relative to this file. Replace "\" by "/" on Windows.
sonar.sources=apps/backend/src,apps/frontend/src,packages
sonar.exclusions=**/node_modules/**,**/dist/**,apps/frontend/src/.umi/**,apps/frontend/src/.umi-production/**,**/*.d.ts

# Backend Jest coverage (lcov report)
sonar.javascript.lcov.reportPaths=apps/backend/coverage/lcov.info
